# Developer apps, browsers, and terminals
[
  "android-commandlinetools"
  "bruno"
  "claude-code"
  "cyberduck"
  "datagrip"
  "gcloud-cli"
  "ghostty@tip"
  "google-chrome"
  "httpie-desktop"
  "lm-studio"
  "orbstack"
  "powershell"
  "visual-studio-code"
  "zed"
  "zed@preview"
  "zen"
]
